### ISSUE TITLE
<Dev> Create main menu for maze

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#1]

**Comment by yijunchung** [comment]
Target Timeline for completion: 30/01/2020

 @s10177952

**Comment by yijunchung** [comment]
@s10177952 
please give me an update on when this source code can be uploaded asap?

**Comment by s10177952** [comment]
Source code uploaded onto GitHub @yijunchung 

30b0463daea57b66b57f6f8175810f06af4e9ba1
