### ISSUE TITLE
QA Tests for Create main menu for maze

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#11]
QA Testing for #1

**Comment by PohWanJun** [comment]
have done test cases for this issue 
[Assignment Test Cases for Issue 1.docx](https://github.com/haraldtan/eti-maze-game/files/4139864/Assignment.Test.Cases.for.Issue.1.docx)

**Comment by haraldtan** [comment]
Keep me updated on when you are able to finish the QA testing? @Eshwar72 
Thanks.

**Comment by Eshwar72** [comment]
Committed the Automated Testing for this issue.
Best Regards
V Eshwar

**Comment by Eshwar72** [comment]
[Assignment.Test.Cases.for.Issue.1.docx](https://github.com/haraldtan/eti-maze-game/files/4174903/Assignment.Test.Cases.for.Issue.1.docx)
Manual Testing for the Issue is done with updated Document

Best Regards,
V Eshwar
