### ISSUE TITLE
QA Tests for Read and load .csv maze file and store in memory

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#12]
QA Testing for #2

**Comment by PohWanJun** [comment]
have done test cases for this issue 
[Assignment Test Cases for Issue 2.docx](https://github.com/haraldtan/eti-maze-game/files/4139865/Assignment.Test.Cases.for.Issue.2.docx)

**Comment by Eshwar72** [comment]
[Assignment.Test.Cases.for.Issue.2.docx](https://github.com/haraldtan/eti-maze-game/files/4173869/Assignment.Test.Cases.for.Issue.2.docx)
Have updated and done test cases manually.
Pushed out Automated Testing.

Best Regards,
V Eshwar

**Comment by Eshwar72** [comment]
[Assignment.Test.Cases.for.Issue.2.docx](https://github.com/haraldtan/eti-maze-game/files/4174923/Assignment.Test.Cases.for.Issue.2.docx)
My sincere apologies, please refer to this updated document for the manual testing results.

Best Regards,
V Eshwar
