### ISSUE TITLE
QA Tests for Output maze stored in memory

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#13]
QA Testing for #3

**Comment by PohWanJun** [comment]
have done test cases for this issue
[Assignment Test Cases for Issue 3.docx](https://github.com/haraldtan/eti-maze-game/files/4143629/Assignment.Test.Cases.for.Issue.3.docx)

**Comment by Eshwar72** [comment]
[Assignment.Test.Cases.for.Issue.3.docx](https://github.com/haraldtan/eti-maze-game/files/4174928/Assignment.Test.Cases.for.Issue.3.docx)
Automated and Manual Testing done for Issue 3.

Best Regards,
V Eshwar
