### ISSUE TITLE
<Dev> Read and load .csv maze file and store in memory

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#2]

**Comment by yijunchung** [comment]
Target Timeline for completion: 04/02/2020

@s10177952

**Comment by s10177952** [comment]
Test cases for feature #2
[Written Test Cases for Feature 2.docx](https://github.com/haraldtan/eti-maze-game/files/4143608/Written.Test.Cases.for.Feature.2.docx)

**Comment by haraldtan** [comment]
You should be checking if the file exists or not, not actually hard coding the name of the file. Also write the test case codes before doing the function itself
<img width="261" alt="Screenshot 2020-02-02 at 20 34 09" src="https://user-images.githubusercontent.com/56616203/73608223-6c0b2900-45fb-11ea-8ec8-1a482460f3ea.png">

**Comment by yijunchung** [comment]
@s10177952  are u checking on the issue above mentioned by the PM? 
by when are u able to fix the issue?
