### ISSUE TITLE
<D-Test> Unit Tests for Create main menu for maze

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#6]
Unit Testing for #1

**Comment by yijunchung** [comment]
[Feature #1.docx](https://github.com/haraldtan/eti-maze-game/files/4132763/Feature.1.docx)

Unit Test cases for Issue #1

**Comment by yijunchung** [comment]
Target deadline for testing:  02/02/2020

@s10177952

**Comment by yijunchung** [comment]
Test cases can be referred from the word document attached above. @s10177952  @haraldtan

**Comment by haraldtan** [comment]
Great, be sure to post the test case results in here once it is done.
Also, try to aim for 31/01/2020 as the QA team needs time to do their acceptance testing too. @yijunchung @s10177952

**Comment by s10177952** [comment]
Seems to be an unknown IO error occurring, not sure how to fix 


![image](https://user-images.githubusercontent.com/58143071/73589725-3be95a80-4515-11ea-81cd-66e38e33bf7b.png)

**Comment by haraldtan** [comment]
The issue is fixed now. The test case should work. @s10177952 
Use pytest -s as a workaround.

**Comment by s10177952** [comment]
Code is uploaded. @yijunchung

**Comment by yijunchung** [comment]
Code tested and analysis attached in the below document. @haraldtan 

[Feature #1 anaylsis.docx](https://github.com/haraldtan/eti-maze-game/files/4143948/Feature.1.anaylsis.docx)

**Comment by haraldtan** [comment]
I'll work with @s10177952 to find a way to avoid the manual inputs. Thanks.

**Comment by yijunchung** [comment]
@s10177952 please refer to this revised written test case instead. Thanks. 

[Feature #1.docx](https://github.com/haraldtan/eti-maze-game/files/4144672/Feature.1.docx)

**Comment by s10177952** [comment]
@yijunchung Testing Completed. Test codes uploaded to GitHub. 
Please check. thx
71684c8
![image](https://user-images.githubusercontent.com/58143071/73613147-c8873c00-462d-11ea-8c55-9485c5293272.png)

**Comment by yijunchung** [comment]
@s10177952 @haraldtan Checked and test. (100% passed.)

![image](https://user-images.githubusercontent.com/56862602/73612301-8a861a00-4625-11ea-9c24-2e0546b9314e.png)

@haraldtan Available to hand in for QA testing.

**Comment by yijunchung** [comment]
[Feature #1 anaylsis.docx](https://github.com/haraldtan/eti-maze-game/files/4144816/Feature.1.anaylsis.docx)

@haraldtan please see the attached feature 1 analysis. Thanks.
