### ISSUE TITLE
<D-Test> Unit Tests for Read and load .csv maze file and store in memory

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#7]
Unit Tests for #2

**Comment by s10177952** [comment]
Test cases for feat
[Written Test Cases for Feature 2.docx](https://github.com/haraldtan/eti-maze-game/files/4143662/Written.Test.Cases.for.Feature.2.docx)
ure #2

**Comment by yijunchung** [comment]
@s10177952  some errors with the above written test cases. Please refer to the attached one. Thanks. 

[Feature #2.docx](https://github.com/haraldtan/eti-maze-game/files/4144617/Feature.2.docx)

@haraldtan FYI too.

**Comment by s10177952** [comment]
@yijunchung Testing completed. Test codes uploaded to GitHub.
Please check . Thx
 71684c8
![image](https://user-images.githubusercontent.com/58143071/73613166-f1a7cc80-462d-11ea-967b-9e4e53cc624e.png)

**Comment by yijunchung** [comment]
@s10177952 @haraldtan Checked and tested. (100% passed.)

![test_read_load](https://user-images.githubusercontent.com/56862602/73612475-13518580-4627-11ea-98cd-1baf7c277a99.png)

@haraldtan Available to hand in for QA testing.

**Comment by yijunchung** [comment]
@haraldtan please see the attached feature 2 analysis. Thanks.

[Feature #2 anaylsis.docx](https://github.com/haraldtan/eti-maze-game/files/4144838/Feature.2.anaylsis.docx)
