### ISSUE TITLE
<D-Test> Unit Tests for Output maze stored in memory

### ISSUE THREAD

**Issue by haraldtan** [haraldtan/eti-maze-game#8]
Unit Testing for #3

**Comment by yijunchung** [comment]
[Feature #3.docx](https://github.com/haraldtan/eti-maze-game/files/4143681/Feature.3.docx)

Unit Test cases for Issue #3

**Comment by yijunchung** [comment]
Test cases can be referred from the word document attached above. @s10177952 @haraldtan

**Comment by yijunchung** [comment]
@s10177952  apologies, some errors on the previous written test cases. Please refer to the attached one instead. Thanks. 

[Feature #3.docx](https://github.com/haraldtan/eti-maze-game/files/4144789/Feature.3.docx)

@haraldtan FYI too.

**Comment by s10177952** [comment]
@yijunchung Testing completed. Test codes uploaded to GitHub.
Please check . Thx
9cf39a0
![image](https://user-images.githubusercontent.com/58143071/73613181-1734d600-462e-11ea-96f0-ee416a74e677.png)

**Comment by yijunchung** [comment]
@s10177952 @haraldtan Checked and tested. (100% passed.)

![test_output_maze](https://user-images.githubusercontent.com/56862602/73612950-9c6abb80-462b-11ea-8741-e2a8ee3c66d7.png)

@haraldtan Available to hand in for QA testing.

**Comment by yijunchung** [comment]
@haraldtan Please see the attached feature 3 analysis. Thanks.

[Feature #3 anaylsis.docx](https://github.com/haraldtan/eti-maze-game/files/4144886/Feature.3.anaylsis.docx)

**Comment by haraldtan** [comment]
Great! I'm closing these issues now. Well done. <img width="806" alt="Screenshot 2020-02-03 at 08 35 01" src="https://user-images.githubusercontent.com/56616203/73618112-1fa60480-4660-11ea-8203-76b3cdac3b2a.png">
